[package]
name = "python_parser"
version = "0.1.0"
edition = "2021"
license-file="LICENSE"
repository="https://github.com/aleph-lang/pythonparser"
description="Python Parser : generate Aleph Syntax Tree."

[dependencies]
aleph-syntax-tree = "0.1.0"
rustpython-parser = "0.2.0"

